/** @type {import('prettier').Config} */
module.exports = {
    semi: true,
    printWidth: 100,
    tabWidth: 2,
    useTabs: false,
    arrowParens: 'avoid',
    singleQuote: true,
    trailingComma: 'all',
    jsxBracketSameLine: false,
    importOrder: [
      '^(react/(.*)$)|^(react$)',
      '^(next/(.*)$)|^(next$)',
      '<THIRD_PARTY_MODULES>',
      '',
      '^types$',
      '^@/types/(.*)$',
      '^@/config/(.*)$',
      '^@/lib/(.*)$',
      '^@/hooks/(.*)$',
      '^@/components/ui/(.*)$',
      '^@/components/(.*)$',
      '^@/styles/(.*)$',
      '^@/app/(.*)$',
      '',
      '^[./]',
    ],
    importOrderSeparation: false,
    importOrderSortSpecifiers: true,
    importOrderBuiltinModulesToTop: true,
    importOrderParserPlugins: ['typescript', 'jsx', 'tsx', 'decorators-legacy'],
    importOrderMergeDuplicateImports: true,
    importOrderCombineTypeAndValueImports: true,
    plugins: ['@ianvs/prettier-plugin-sort-imports'],
  };
  